[default.global.parameters]
stack_name = "feriaescolar-backend"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name = "feriaescolar-backend"
s3_bucket = "feriaescolar-sam-artifacts"
s3_prefix = "feriaescolar"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
resolve_s3 = false